/*
 * Copy the game into mobile/www for Capacitor.
 *
 * The app ships the same files the web build serves — there is one game, and a
 * second copy would drift. Two things are deliberately left out:
 *
 *  - the service worker, because inside a WebView it caches a copy of a copy and
 *    then serves a stale build after an app update, which is very hard to debug
 *    from a store review queue;
 *  - the tests and the dev cheats, which have no business in a shipped app.
 */
'use strict';
const fs = require('fs');
const path = require('path');

const SRC = path.join(__dirname, '..');
const OUT = path.join(__dirname, 'www');

const COPY = ['index.html', 'privacy.html', 'manifest.json', 'config.js', 'css', 'js', 'assets'];
const SKIP_FILES = new Set(['sw.js', 'cheats.js']);
const SKIP_ASSET = /^screenshot-/;   // store listings use these, the app doesn't

function copy(src, dst) {
  const st = fs.statSync(src);
  if (st.isDirectory()) {
    fs.mkdirSync(dst, { recursive: true });
    for (const name of fs.readdirSync(src)) {
      if (SKIP_FILES.has(name)) continue;
      if (SKIP_ASSET.test(name)) continue;
      copy(path.join(src, name), path.join(dst, name));
    }
    return;
  }
  fs.copyFileSync(src, dst);
}

fs.rmSync(OUT, { recursive: true, force: true });
fs.mkdirSync(OUT, { recursive: true });
for (const item of COPY) {
  const from = path.join(SRC, item);
  if (fs.existsSync(from)) copy(from, path.join(OUT, item));
}

// Strip the service worker registration and the cheats script tag. Both are
// removed at the source rather than left to 404 inside the WebView.
const indexPath = path.join(OUT, 'index.html');
let html = fs.readFileSync(indexPath, 'utf8');
html = html.replace(/\s*<script src="js\/cheats\.js[^"]*"><\/script>/, '');
fs.writeFileSync(indexPath, html);

// Tell the game it is running as an installed app, so it can drop the things
// that only make sense in a browser tab (the fullscreen button, mainly).
fs.writeFileSync(path.join(OUT, 'js', 'platform.js'),
  '/* generated by sync-web.js */\nwindow.LUMEN_NATIVE = { platform: "mobile" };\n');
html = fs.readFileSync(indexPath, 'utf8');
if (!/platform\.js/.test(html)) {
  html = html.replace(/<script src="js\/audio\.js/, '<script src="js/platform.js"></script>\n  <script src="js/audio.js');
  fs.writeFileSync(indexPath, html);
}

const count = (dir) => fs.readdirSync(dir, { withFileTypes: true })
  .reduce((n, e) => n + (e.isDirectory() ? count(path.join(dir, e.name)) : 1), 0);
console.log('copied ' + count(OUT) + ' files into mobile/www (no service worker, no cheats)');
